# Generated by Django 4.1.3 on 2022-11-25 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="nse_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strike_price", models.FloatField()),
                ("bid_price", models.FloatField()),
                ("buy_time", models.DateTimeField(auto_now=True)),
                ("live_price", models.FloatField()),
                ("pcr_value", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="nse_profit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strike_price", models.FloatField()),
                ("bid_price", models.FloatField()),
                ("buy_time", models.DateTimeField(auto_now=True)),
                ("live_price", models.FloatField()),
                ("pcr_value", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="profit_margin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percentage", models.IntegerField()),
                ("option", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="nse_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_strike_price", models.FloatField()),
                ("live_Strike_price", models.FloatField()),
                ("buy_price", models.FloatField()),
                ("sell_price", models.FloatField()),
                ("stop_loseprice", models.FloatField()),
                ("live_brid_price", models.FloatField()),
                ("exit_price", models.FloatField(null=True)),
                ("buy_time", models.DateTimeField(auto_now_add=True)),
                ("sell_buy_time", models.DateTimeField(null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("BUY", "BUY"), ("SELL", "SELL"), ("empty", "empty")],
                        default="empty",
                        max_length=50,
                    ),
                ),
                (
                    "percentage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nse_app.profit_margin",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="banknifty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_strike_price", models.FloatField()),
                ("live_Strike_price", models.FloatField()),
                ("buy_price", models.FloatField()),
                ("sell_price", models.FloatField()),
                ("stop_loseprice", models.FloatField()),
                ("live_brid_price", models.FloatField()),
                ("exit_price", models.FloatField(null=True)),
                ("buy_time", models.DateTimeField(auto_now_add=True)),
                ("sell_buy_time", models.DateTimeField(null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("BUY", "BUY"), ("SELL", "SELL"), ("empty", "empty")],
                        default="empty",
                        max_length=50,
                    ),
                ),
                (
                    "percentage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nse_app.profit_margin",
                    ),
                ),
            ],
        ),
    ]
