# Generated by Django 4.1.3 on 2022-11-14 09:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nse_data',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strike_price', models.IntegerField()),
                ('bid_price', models.IntegerField()),
                ('buy_time', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
