# Generated by Django 4.1.3 on 2022-11-14 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nse_model',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strike_price', models.IntegerField()),
                ('bid_price', models.IntegerField()),
                ('buy_time', models.TimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='nse_data',
        ),
    ]
