# Generated by Django 4.1.3 on 2022-11-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0002_nse_model_delete_nse_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nse_model',
            name='bid_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nse_model',
            name='strike_price',
            field=models.FloatField(),
        ),
    ]
