# Generated by Django 4.1.3 on 2022-12-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nse_app", "0002_rename_percentage_profit_margin_percent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profit_margin",
            old_name="percent",
            new_name="percentage",
        ),
    ]
