# Generated by Django 4.1.5 on 2023-01-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0002_stock_detail_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_detail',
            name='buy_pcr',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stock_detail',
            name='exit_pcr',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stock_detail',
            name='net_p_l',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stock_detail',
            name='qnty',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
