# Generated by Django 4.1.3 on 2022-11-15 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0003_alter_nse_model_bid_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='nse_profit',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strike_price', models.FloatField()),
                ('bid_price', models.FloatField()),
                ('buy_time', models.DateTimeField(auto_now=True)),
                ('live_price', models.FloatField()),
                ('pcr_value', models.FloatField()),
                ('stop_loss', models.FloatField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='nse_model',
            name='live_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nse_model',
            name='pcr_value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nse_model',
            name='stop_loss',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nse_model',
            name='buy_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
