# Generated by Django 4.1.3 on 2022-12-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nse_app", "0003_rename_percent_profit_margin_percentage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="profit_margin",
            new_name="nse_setting",
        ),
        migrations.RenameModel(
            old_name="banknifty",
            new_name="stock_detail",
        ),
        migrations.DeleteModel(
            name="nse_data",
        ),
        migrations.RemoveField(
            model_name="nse_model",
            name="percentage",
        ),
        migrations.DeleteModel(
            name="nse_profit",
        ),
        migrations.DeleteModel(
            name="nse_model",
        ),
    ]
