# Generated by Django 4.1.5 on 2023-01-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0004_live_banknifty_at_set_pcr_live_banknifty_live_pcr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='live_banknifty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='live',
            name='live_nifty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='live',
            name='live_stock',
            field=models.BooleanField(default=False),
        ),
    ]
