# Generated by Django 4.1.3 on 2022-11-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0004_nse_profit_nse_model_live_price_nse_model_pcr_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nse_model',
            name='stop_loss',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nse_profit',
            name='stop_loss',
            field=models.FloatField(null=True),
        ),
    ]
