# Generated by Django 4.1.5 on 2023-02-09 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0007_delete_category_alter_live_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='live',
            table='live-settings',
        ),
        migrations.AlterModelTable(
            name='nse_setting',
            table='settings',
        ),
        migrations.AlterModelTable(
            name='pcr_option',
            table='pcr-options',
        ),
        migrations.AlterModelTable(
            name='pcr_stock_name',
            table='pcr-stockName',
        ),
        migrations.AlterModelTable(
            name='stock_detail',
            table='stocks-details',
        ),
    ]
