# Generated by Django 4.1.5 on 2023-02-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0009_alter_live_table_alter_pcr_option_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcr_option',
            old_name='banknifty_at_set_pcr',
            new_name='banknifty_at_set_pcr_CALL',
        ),
        migrations.RenameField(
            model_name='pcr_option',
            old_name='banknifty_pcr_stoploss',
            new_name='banknifty_pcr_stoploss_CALL',
        ),
        migrations.AddField(
            model_name='pcr_option',
            name='banknifty_at_set_pcr_PUT',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
