# Generated by Django 4.1.3 on 2022-11-21 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nse_app", "0009_alter_nse_buy_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nse",
            name="buy_status",
        ),
    ]
