# Generated by Django 4.1.5 on 2023-02-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0010_rename_banknifty_at_set_pcr_pcr_option_banknifty_at_set_pcr_call_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcr_option',
            name='banknifty_pcr_stoploss_PUT',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
