# Generated by Django 4.1.5 on 2023-03-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0011_pcr_option_banknifty_pcr_stoploss_put'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcr_option',
            old_name='banknifty_at_set_pcr_CALL',
            new_name='AtSetPcr',
        ),
        migrations.RenameField(
            model_name='pcr_option',
            old_name='banknifty_live_pcr',
            new_name='LivePcr',
        ),
        migrations.RenameField(
            model_name='pcr_option',
            old_name='banknifty_pcr_stoploss_CALL',
            new_name='PcrStopLoss',
        ),
        migrations.RemoveField(
            model_name='pcr_option',
            name='banknifty_at_set_pcr_PUT',
        ),
        migrations.RemoveField(
            model_name='pcr_option',
            name='banknifty_pcr_stoploss_PUT',
        ),
        migrations.RemoveField(
            model_name='pcr_option',
            name='nifty_at_set_pcr',
        ),
        migrations.RemoveField(
            model_name='pcr_option',
            name='nifty_live_pcr',
        ),
        migrations.RemoveField(
            model_name='pcr_option',
            name='nifty_pcr_stoploss',
        ),
        migrations.AddField(
            model_name='pcr_option',
            name='OptionName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
