# Generated by Django 4.1.3 on 2022-11-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nse_app", "0011_nse_buy_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nse",
            name="buy_status",
            field=models.CharField(
                blank=True,
                choices=[("BUY", "BUY"), ("SELL", "SELL"), ("empty", "empty")],
                default="empty",
                max_length=50,
            ),
        ),
    ]
