# Generated by Django 4.1.3 on 2022-11-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nse_app", "0012_alter_nse_buy_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="nse",
            name="shell_bid_price",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nse",
            name="shell_buy_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="nse",
            name="shell_strike_price",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="nse",
            name="buy_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
