# Generated by Django 4.1.5 on 2023-03-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0012_rename_banknifty_at_set_pcr_call_pcr_option_atsetpcr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pcr_option',
        ),
    ]
