# Generated by Django 4.1.5 on 2023-03-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0013_delete_pcr_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='pcr_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OptionName', models.CharField(max_length=50)),
                ('AtSetPcr', models.BooleanField(blank=True, default=False, null=True)),
                ('PcrStopLoss', models.FloatField(blank=True, null=True)),
                ('LivePcr', models.FloatField(blank=True, default=0)),
            ],
            options={
                'db_table': 'pcr_options',
            },
        ),
    ]
