# Generated by Django 4.1.3 on 2022-11-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nse_app", "0015_alter_nse_shell_bid_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nse",
            name="shell_buy_time",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
