# Generated by Django 4.1.5 on 2023-03-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0015_nse_setting_you_can_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_for_buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocks_name', models.CharField(max_length=100)),
                ('call_or_put', models.CharField(blank=True, choices=[('CALL', 'CALL'), ('PUT', 'PUT'), ('NA', 'NA')], max_length=50)),
            ],
        ),
    ]
