# Generated by Django 4.1.5 on 2023-03-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0016_stock_for_buy'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stock_for_buy',
            table='stock_for_buy',
        ),
    ]
