# Generated by Django 4.1.3 on 2022-11-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nse_app", "0016_alter_nse_shell_buy_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nse",
            name="shell_buy_time",
            field=models.DateTimeField(null=True),
        ),
    ]
