# Generated by Django 4.1.5 on 2023-03-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0018_pcr_values_stock_for_buy_difference_ce_pe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_for_buy',
            name='difference_ce_pe',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
