# Generated by Django 4.1.5 on 2023-03-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0019_alter_stock_for_buy_difference_ce_pe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='live',
            old_name='live_stock',
            new_name='live_stock_ce',
        ),
        migrations.AddField(
            model_name='live',
            name='live_stock_pe',
            field=models.BooleanField(default=False),
        ),
    ]
