# Generated by Django 4.1.5 on 2023-03-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0020_rename_live_stock_live_live_stock_ce_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='extra_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcr_isupdating', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'extra_setting',
            },
        ),
    ]
