# Generated by Django 4.1.5 on 2023-04-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0022_stock_for_buy_ce_side_persnt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_price', models.FloatField(blank=True, null=True)),
                ('created_at', models.TimeField(auto_now=True, null=True)),
            ],
        ),
    ]
