# Generated by Django 4.1.5 on 2023-04-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0023_livedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_basezone', models.BooleanField(default=False)),
                ('base_price', models.FloatField()),
                ('stop_loss_price', models.FloatField()),
            ],
            options={
                'db_table': 'BaseZone',
            },
        ),
        migrations.AlterModelTable(
            name='livedata',
            table='LiveData',
        ),
    ]
