# Generated by Django 4.1.5 on 2023-04-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0025_livedata_in_basezone_alter_basezone_base_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseZoneNifty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_basezone', models.BooleanField(blank=True, default=False, null=True)),
                ('base_price', models.FloatField(blank=True, null=True)),
                ('stop_loss_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'BaseZone_Nifty',
            },
        ),
        migrations.RenameModel(
            old_name='BaseZone',
            new_name='BaseZoneBanknifty',
        ),
        migrations.AlterModelTable(
            name='basezonebanknifty',
            table='BaseZone_Banknifty',
        ),
    ]
