# Generated by Django 4.1.5 on 2023-04-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0026_basezonenifty_rename_basezone_basezonebanknifty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveDataNifty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_price', models.FloatField(blank=True, null=True)),
                ('created_at', models.TimeField(auto_now=True, null=True)),
                ('in_basezone', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'LiveData_Nifty',
            },
        ),
        migrations.RenameModel(
            old_name='LiveData',
            new_name='LiveDataBankNifty',
        ),
        migrations.AlterModelTable(
            name='livedatabanknifty',
            table='LiveData_Banknifty',
        ),
    ]
