# Generated by Django 4.1.5 on 2023-05-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0027_livedatanifty_rename_livedata_livedatabanknifty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResistanceZone_Banknifty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_resistance', models.BooleanField(blank=True, default=False, null=True)),
                ('resistance_price', models.FloatField(blank=True, null=True)),
                ('stop_loss_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ResistanceZone_Banknifty',
            },
        ),
        migrations.CreateModel(
            name='ResistanceZone_Nifty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_resistance', models.BooleanField(blank=True, default=False, null=True)),
                ('resistance_price', models.FloatField(blank=True, null=True)),
                ('stop_loss_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ResistanceZone_Nifty',
            },
        ),
        migrations.AddField(
            model_name='livedatabanknifty',
            name='in_resistance',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='livedatanifty',
            name='in_resistance',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
