# Generated by Django 4.1.5 on 2023-08-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0029_accountcredential'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountcredential',
            table='account_credential',
        ),
    ]
