# Generated by Django 4.1.5 on 2023-08-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0030_alter_accountcredential_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcredential',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
