# Generated by Django 4.1.5 on 2023-08-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0031_alter_accountcredential_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_detail',
            old_name='qnty',
            new_name='qty',
        ),
        migrations.RemoveField(
            model_name='stock_detail',
            name='net_p_l',
        ),
        migrations.AddField(
            model_name='stock_detail',
            name='order_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
