# Generated by Django 4.1.5 on 2023-08-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0032_rename_qnty_stock_detail_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_detail',
            name='base_strike_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='stock_detail',
            name='buy_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='stock_detail',
            name='live_Strike_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='stock_detail',
            name='live_brid_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='stock_detail',
            name='sell_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='stock_detail',
            name='stop_loseprice',
            field=models.FloatField(blank=True),
        ),
    ]
