# Generated by Django 4.1.5 on 2023-09-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0034_alter_stock_detail_base_strike_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_detail',
            name='type',
            field=models.CharField(blank=True, choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('NA', 'NA')], default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock_detail',
            name='status',
            field=models.CharField(blank=True, choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('NA', 'NA')], default='empty', max_length=50),
        ),
    ]
