# Generated by Django 4.1.5 on 2023-09-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0035_stock_detail_type_alter_stock_detail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_detail',
            name='status',
            field=models.CharField(blank=True, choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('NA', 'NA')], default='NA', max_length=50),
        ),
    ]
