# Generated by Django 4.1.5 on 2023-09-13 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0037_stock_detail_oi_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_detail',
            name='percentage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nse_app.nse_setting'),
        ),
    ]
