# Generated by Django 4.1.5 on 2023-09-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse_app', '0039_alter_stock_detail_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nse_setting',
            name='loss_percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nse_setting',
            name='profit_percentage',
            field=models.FloatField(),
        ),
    ]
